FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /app

COPY DiscordBot.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/samples:3.0 AS runtime
WORKDIR /app
COPY --from=build /bin/Release/netcoreapp3.0t ./
ENTRYPOINT ["dotnet", "DiscordBot.dll"]